language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3

install:
  - composer selfupdate
  - composer install

script:
  - phpunit --configuration native.xml
  - phpunit --configuration mbstring.xml

notifications:
  email:
    recipients:
      - poisoncorpsee@gmail.com

    on_success: always
    on_failure: always
