language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
    allow_failures:
        - php:
          - hhvm
          - 5.6

install: composer install
script:
  - phpunit --configuration native.xml   --coverage-text
  - phpunit --configuration mbstring.xml --coverage-text
